import { Link, useLocation } from "wouter";
import { Activity, BarChart3, Bell, ChevronDown, CircleHelp, ClipboardList, Command, Database, FileClock, Gauge, Layers3, Menu, Network, PanelLeftClose, PanelLeftOpen, Play, Settings2, ShieldCheck, Sparkles, Table2, X } from "lucide-react";
import type { ReactNode } from "react";
import { useState } from "react";
import { cn } from "@/lib/utils";

const navItems = [
  { href: "/dashboard", label: "Overview", icon: Gauge, section: "COMMAND CENTER" },
  { href: "/transactions", label: "Transactions", icon: Table2, section: "COMMAND CENTER" },
  { href: "/recovery", label: "Recovery", icon: Activity, section: "COMMAND CENTER" },
  { href: "/analytics", label: "Analytics", icon: BarChart3, section: "COMMAND CENTER" },
  { href: "/ai-decisions", label: "AI Decisions", icon: Sparkles, section: "INTELLIGENCE" },
  { href: "/audit", label: "Audit Trail", icon: FileClock, section: "INTELLIGENCE" },
];

export function BrandMark({ compact = false }: { compact?: boolean }) {
  return <div className="flex items-center gap-2.5" aria-label="ReviveAI home"><div className="grid h-8 w-8 place-items-center rounded-[10px] border border-[#6DE7F2]/30 bg-[#6DE7F2]/[0.08] text-[#6DE7F2] shadow-[0_0_22px_rgba(109,231,242,.12)]"><img src="/images/reviveai-logo-mark.png" alt="" className="h-5 w-5 object-contain" /><svg viewBox="0 0 32 32" className="hidden h-5 w-5" aria-hidden="true"><path d="M8 22.4V9.6a2 2 0 0 1 2-2h5.25c4.95 0 7.75 2.17 7.75 5.9 0 2.15-1.05 3.72-3.06 4.65L23.5 24h-4.3l-2.85-4.98h-4.05V24H8v-1.6Zm4.3-5.2h2.75c2.25 0 3.5-1 3.5-2.84 0-1.8-1.25-2.76-3.5-2.76H12.3v5.6Z" fill="currentColor"/><path d="M9 25.5c4.2 2.7 10 2.2 13.7-1.4" fill="none" stroke="currentColor" strokeLinecap="round" strokeWidth="1.4" opacity=".75"/></svg></div>{!compact && <div className="leading-none"><div className="font-display text-[15px] font-semibold tracking-[.22em] text-[#E7F4F7]">REVIVE<span className="text-[#6DE7F2]">AI</span></div><div className="mt-1 font-mono text-[8px] tracking-[.22em] text-[#78909D]">REVENUE SYSTEMS</div></div>}</div>;
}

export function StatusPill({ label, tone = "info" }: { label: string; tone?: "success" | "warning" | "danger" | "info" | "neutral" }) {
  const colors = { success: "border-[#81E6A8]/20 bg-[#81E6A8]/[0.08] text-[#81E6A8]", warning: "border-[#F0B36B]/20 bg-[#F0B36B]/[0.08] text-[#F0B36B]", danger: "border-[#FF8C88]/20 bg-[#FF8C88]/[0.08] text-[#FF8C88]", info: "border-[#6DE7F2]/20 bg-[#6DE7F2]/[0.08] text-[#6DE7F2]", neutral: "border-white/10 bg-white/[0.04] text-[#9BB0B9]" };
  return <span className={cn("inline-flex items-center gap-2 rounded-full border px-2.5 py-1 font-mono text-[9px] font-medium uppercase tracking-[.12em]", colors[tone])}><span className={cn("status-dot", tone === "neutral" ? "bg-[#72858e]" : tone)} />{label}</span>;
}

export function AppShell({ children, title, eyebrow, action }: { children: ReactNode; title: string; eyebrow?: string; action?: ReactNode }) {
  const [collapsed, setCollapsed] = useState(false);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [location] = useLocation();
  return <div className="signal-app noise min-h-screen">
    <aside className={cn("sidebar-scroll fixed inset-y-0 left-0 z-40 hidden flex-col overflow-y-auto border-r border-white/[0.08] bg-[#08131c]/95 px-3 py-5 backdrop-blur-xl transition-all duration-200 lg:flex", collapsed ? "w-[76px]" : "w-[250px]") }>
      <div className={cn("mb-9 flex items-center", collapsed ? "justify-center" : "justify-between px-2")}><BrandMark compact={collapsed} />{!collapsed && <button aria-label="Collapse navigation" className="rounded-md p-2 text-[#6E858E] transition hover:bg-white/[0.05] hover:text-white" onClick={() => setCollapsed(true)}><PanelLeftClose className="h-4 w-4" /></button>}</div>
      {collapsed && <button aria-label="Expand navigation" className="mb-6 mx-auto rounded-md p-2 text-[#6E858E] transition hover:bg-white/[0.05] hover:text-white" onClick={() => setCollapsed(false)}><PanelLeftOpen className="h-4 w-4" /></button>}
      <nav className="flex-1">
        {["COMMAND CENTER", "INTELLIGENCE"].map((section) => <div key={section} className="mb-7"><div className={cn("mb-2 px-2 font-mono text-[9px] tracking-[.18em] text-[#536A75]", collapsed && "text-center text-[7px] tracking-[0]")}>{collapsed ? "—" : section}</div>{navItems.filter((item) => item.section === section).map(({ href, label, icon: Icon }) => { const active = location === href || (href === "/dashboard" && location === "/"); return <Link key={href} href={href} onClick={() => setMobileOpen(false)} className={cn("group mb-1 flex items-center gap-3 rounded-lg px-2.5 py-2.5 text-[13px] transition", active ? "bg-[#6DE7F2]/[0.1] text-[#E7F4F7] shadow-[inset_2px_0_0_#6DE7F2]" : "text-[#80959E] hover:bg-white/[0.04] hover:text-[#DDEDEF]", collapsed && "justify-center px-0")}><Icon className={cn("h-[17px] w-[17px]", active ? "text-[#6DE7F2]" : "text-[#607782] group-hover:text-[#9BB0B9]")} />{!collapsed && <span>{label}</span>}</Link>})}</div>)}
        <div><div className={cn("mb-2 px-2 font-mono text-[9px] tracking-[.18em] text-[#536A75]", collapsed && "text-center text-[7px] tracking-[0]")}>{collapsed ? "—" : "SYSTEM"}</div><Link href="/settings" className={cn("group mb-1 flex items-center gap-3 rounded-lg px-2.5 py-2.5 text-[13px] text-[#80959E] transition hover:bg-white/[0.04] hover:text-[#DDEDEF]", collapsed && "justify-center px-0")}><Settings2 className="h-[17px] w-[17px] text-[#607782] group-hover:text-[#9BB0B9]" />{!collapsed && "Settings"}</Link></div>
      </nav>
      <div className={cn("mt-8 rounded-xl border border-[#81E6A8]/15 bg-[#81E6A8]/[0.035] p-3", collapsed && "border-0 bg-transparent p-1")}>{collapsed ? <div className="mx-auto mt-1 h-2 w-2 rounded-full bg-[#81E6A8] shadow-[0_0_12px_rgba(129,230,168,.6)]" /> : <><div className="mb-2 flex items-center justify-between"><span className="font-mono text-[9px] tracking-[.14em] text-[#81E6A8]">SYSTEM STATUS</span><span className="status-dot success" /></div><div className="text-[12px] text-[#B5C8CC]">All services operational</div><div className="mt-2 font-mono text-[9px] text-[#6C858E]">Last sync · 14 sec ago</div></>}</div>
      <div className={cn("mt-5 flex items-center gap-2 border-t border-white/[0.07] pt-4", collapsed ? "justify-center" : "px-2")}><div className="grid h-8 w-8 place-items-center rounded-full bg-gradient-to-br from-[#3D7181] to-[#182D38] font-display text-[11px] font-semibold text-[#D5FAFF]">AM</div>{!collapsed && <div className="min-w-0 flex-1"><div className="truncate text-[12px] text-[#D6E6E8]">Aarav Mehta</div><div className="truncate font-mono text-[9px] text-[#607782]">Meridian Commerce</div></div>}</div>
    </aside>
    {mobileOpen && <div className="fixed inset-0 z-30 bg-black/60 lg:hidden" onClick={() => setMobileOpen(false)} />}
    <aside className={cn("fixed inset-y-0 left-0 z-40 flex w-[270px] flex-col border-r border-white/[0.08] bg-[#08131c] px-4 py-5 transition-transform lg:hidden", mobileOpen ? "translate-x-0" : "-translate-x-full")}><div className="mb-8 flex items-center justify-between"><BrandMark /><button onClick={() => setMobileOpen(false)} className="p-2 text-[#6E858E]"><X className="h-5 w-5" /></button></div><nav className="space-y-1">{navItems.map(({ href, label, icon: Icon }) => <Link key={href} href={href} className="flex items-center gap-3 rounded-lg px-3 py-3 text-sm text-[#A7BBC0] hover:bg-white/[0.05]"><Icon className="h-4 w-4 text-[#6DE7F2]" />{label}</Link>)}</nav></aside>
    <div className={cn("min-h-screen transition-[padding] duration-200", collapsed ? "lg:pl-[76px]" : "lg:pl-[250px]")}>
      <header className="sticky top-0 z-20 flex h-[72px] items-center justify-between border-b border-white/[0.08] bg-[#071018]/80 px-4 backdrop-blur-xl sm:px-6 lg:px-10"><div className="flex items-center gap-3"><button aria-label="Open navigation" onClick={() => setMobileOpen(true)} className="rounded-lg border border-white/[0.1] p-2 text-[#A7BBC0] lg:hidden"><Menu className="h-4 w-4" /></button><div className="hidden h-5 w-px bg-white/10 lg:block" /><div><div className="font-mono text-[9px] tracking-[.18em] text-[#607782]">REVIVEAI / {eyebrow || "COMMAND CENTER"}</div><h1 className="mt-1 font-display text-[15px] font-medium tracking-[-.01em] text-[#E4F2F4] sm:text-[17px]">{title}</h1></div></div><div className="flex items-center gap-2 sm:gap-4"><div className="hidden items-center gap-2 xl:flex"><StatusPill label="AI Agent operational" tone="success" /><span className="font-mono text-[9px] text-[#617782]">DEMO MODE</span></div>{action}<button aria-label="Notifications" className="relative rounded-lg p-2 text-[#80959E] transition hover:bg-white/[0.05] hover:text-white"><Bell className="h-[17px] w-[17px]" /><span className="absolute right-1.5 top-1.5 h-1.5 w-1.5 rounded-full bg-[#6DE7F2]" /></button><button aria-label="Open help" className="hidden rounded-lg p-2 text-[#80959E] transition hover:bg-white/[0.05] hover:text-white sm:block"><CircleHelp className="h-[17px] w-[17px]" /></button></div></header>
      <main className="mx-auto w-full max-w-[1540px] px-4 py-6 sm:px-6 lg:px-10 lg:py-8">{children}</main>
    </div>
  </div>;
}

export function SectionLabel({ children, action }: { children: ReactNode; action?: ReactNode }) { return <div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2.5"><span className="h-1.5 w-1.5 rounded-full bg-[#6DE7F2] shadow-[0_0_10px_rgba(109,231,242,.6)]" /><span className="font-mono text-[10px] font-medium tracking-[.18em] text-[#89A4AD]">{children}</span></div>{action}</div>; }

export function MetricCard({ label, value, delta, icon: Icon, tone = "signal", data }: { label: string; value: string; delta: string; icon: typeof Activity; tone?: "signal" | "success" | "warning" | "danger"; data: number[] }) {
  const color = tone === "success" ? "#81E6A8" : tone === "warning" ? "#F0B36B" : tone === "danger" ? "#FF8C88" : "#6DE7F2";
  const points = data.map((point, index) => `${index * (100 / (data.length - 1))},${42 - point * 30}`).join(" ");
  return <div className="glass-panel group relative overflow-hidden rounded-xl p-5 transition duration-200 hover:-translate-y-0.5"><div className="absolute -right-8 -top-8 h-24 w-24 rounded-full opacity-[.06] blur-2xl" style={{ background: color }} /><div className="flex items-start justify-between"><div className="font-mono text-[10px] tracking-[.12em] text-[#78919B]">{label}</div><div className="rounded-lg border border-white/[0.08] p-2" style={{ color, background: `${color}0D` }}><Icon className="h-4 w-4" /></div></div><div className="mt-4 flex items-end justify-between gap-3"><div><div className="font-display text-[25px] font-semibold tracking-[-.04em] text-[#EFFBFC]">{value}</div><div className="mt-2 flex items-center gap-1.5 font-mono text-[10px]" style={{ color }}><span>{delta.startsWith("-") ? "↓" : "↑"}</span>{delta} <span className="text-[#617782]">vs last 30d</span></div></div><svg viewBox="0 0 100 45" className="h-11 w-[94px] overflow-visible" preserveAspectRatio="none" aria-hidden="true"><polyline points={points} fill="none" stroke={color} strokeWidth="1.7" vectorEffect="non-scaling-stroke" className="draw-in" /><polyline points={`0,45 ${points} 100,45`} fill={color} opacity=".06" /></svg></div></div>;
}

export function PageIntro({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-5 border-b border-white/[0.08] pb-7 md:flex-row md:items-end"><div><div className="mb-3 font-mono text-[10px] tracking-[.18em] text-[#6DE7F2]">{eyebrow}</div><h2 className="font-display text-[28px] font-medium tracking-[-.04em] text-[#EDF9FA] sm:text-[34px]">{title}</h2><p className="mt-2 max-w-2xl text-[13px] leading-6 text-[#8199A3]">{description}</p></div>{action}</div>; }

export function EmptyState({ icon: Icon = Database, title, text }: { icon?: typeof Database; title: string; text: string }) { return <div className="flex min-h-[260px] flex-col items-center justify-center rounded-xl border border-dashed border-white/[0.13] bg-white/[0.015] px-6 text-center"><Icon className="mb-4 h-7 w-7 text-[#526C77]" /><div className="font-display text-[15px] text-[#D8E9EB]">{title}</div><p className="mt-2 max-w-sm text-[12px] leading-5 text-[#6F8791]">{text}</p></div>; }
