import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { AnalyticsSnapshot, ChartPoint } from "@/lib/types";

const formatCompact = (value: number) => value >= 100000 ? `₹${(value / 100000).toFixed(1)}L` : `₹${(value / 1000).toFixed(0)}k`;
const tooltipStyle = { background: "#0C1B25", border: "1px solid rgba(109,231,242,.2)", borderRadius: 10, color: "#E7F4F7", fontSize: 11, boxShadow: "0 14px 34px rgba(0,0,0,.3)" };

export function RecoveryTrendChart({ data, compact = false }: { data: ChartPoint[]; compact?: boolean }) {
  return <div className={compact ? "h-[230px] w-full" : "h-[320px] w-full"}><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 12, right: 8, left: -18, bottom: 0 }}><defs><linearGradient id="riskFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#F0B36B" stopOpacity={.22} /><stop offset="100%" stopColor="#F0B36B" stopOpacity={0} /></linearGradient><linearGradient id="recoveredFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6DE7F2" stopOpacity={.18} /><stop offset="100%" stopColor="#6DE7F2" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="rgba(148,185,197,.08)" vertical={false} /><XAxis dataKey="label" tick={{ fill: "#6F8791", fontSize: 10 }} axisLine={false} tickLine={false} minTickGap={20} /><YAxis tick={{ fill: "#6F8791", fontSize: 10 }} axisLine={false} tickLine={false} tickFormatter={formatCompact} width={48} /><Tooltip contentStyle={tooltipStyle} formatter={(value: number, name: string) => [formatCompact(value), name === "risk" ? "Revenue at risk" : "Recovered"]} labelStyle={{ color: "#B8CED3", marginBottom: 4 }} /><Area type="monotone" dataKey="risk" stroke="#F0B36B" strokeWidth={1.5} fill="url(#riskFill)" animationDuration={1200} /><Area type="monotone" dataKey="recovered" stroke="#6DE7F2" strokeWidth={2} fill="url(#recoveredFill)" animationDuration={1200} /></AreaChart></ResponsiveContainer></div>;
}

export function FailureMixChart({ data }: { data: AnalyticsSnapshot["failureTypes"] }) {
  return <div className="h-[220px] w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} layout="vertical" margin={{ top: 4, right: 10, left: 12, bottom: 0 }}><CartesianGrid stroke="rgba(148,185,197,.08)" horizontal={false} /><XAxis type="number" domain={[0, 100]} hide /><YAxis type="category" dataKey="name" tick={{ fill: "#8EA4AC", fontSize: 10 }} width={100} axisLine={false} tickLine={false} /><Tooltip cursor={{ fill: "rgba(109,231,242,.04)" }} contentStyle={tooltipStyle} formatter={(value: number) => [`${value}%`, "Recovered"]} /><Bar dataKey="recovered" fill="#6DE7F2" radius={[0, 5, 5, 0]} barSize={12} animationDuration={900} /></BarChart></ResponsiveContainer></div>;
}

export function PaymentMethodsChart({ data }: { data: AnalyticsSnapshot["paymentMethods"] }) {
  return <div className="flex h-[220px] items-center gap-6"><div className="h-full min-w-[180px] flex-1"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius={58} outerRadius={78} paddingAngle={4} stroke="none" animationDuration={900}>{data.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip contentStyle={tooltipStyle} formatter={(value: number) => [`${value}%`, "Volume"]} /></PieChart></ResponsiveContainer></div><div className="space-y-3">{data.map((item) => <div key={item.name} className="flex items-center gap-2.5"><span className="h-2 w-2 rounded-full" style={{ background: item.color }} /><span className="text-[11px] text-[#9BB0B9]">{item.name}</span><span className="font-mono text-[10px] text-[#DDEDEF]">{item.value}%</span></div>)}</div></div>;
}

export function ProbabilityChart({ data }: { data: AnalyticsSnapshot["probabilityDistribution"] }) { return <div className="h-[190px] w-full"><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{ top: 10, right: 4, left: -25, bottom: 0 }}><CartesianGrid stroke="rgba(148,185,197,.08)" vertical={false} /><XAxis dataKey="bucket" tick={{ fill: "#6F8791", fontSize: 9 }} axisLine={false} tickLine={false} /><YAxis tick={{ fill: "#6F8791", fontSize: 9 }} axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} formatter={(value: number) => [value, "Transactions"]} /><Bar dataKey="count" fill="#8295FF" radius={[4, 4, 0, 0]} barSize={26} animationDuration={900} /></BarChart></ResponsiveContainer></div>; }

export function RecoveryFunnel() { const stages = [{ label: "Revenue at risk", count: "1,000", width: "100%", color: "#526C77" }, { label: "AI diagnosed", count: "812", width: "81%", color: "#657B9A" }, { label: "Eligible", count: "621", width: "62%", color: "#8295FF" }, { label: "Recovery attempted", count: "358", width: "43%", color: "#6DE7F2" }, { label: "Recovered", count: "241", width: "28%", color: "#81E6A8" }]; return <div className="space-y-2.5">{stages.map((stage, index) => <div key={stage.label} className="group flex items-center gap-3"><div className="w-[112px] shrink-0 text-right font-mono text-[9px] uppercase tracking-[.08em] text-[#78919B]">{stage.label}</div><div className="relative h-9 flex-1 overflow-hidden bg-[#11212B]" style={{ clipPath: index === 0 ? "polygon(0 0, 100% 0, 96% 100%, 4% 100%)" : index === stages.length - 1 ? "polygon(14% 0, 86% 0, 100% 100%, 0 100%)" : "polygon(5% 0, 95% 0, 88% 100%, 12% 100%)" }}><div className="h-full transition-all duration-500 group-hover:brightness-125" style={{ width: stage.width, background: `linear-gradient(90deg, ${stage.color}22, ${stage.color}AA)` }} /><div className="absolute inset-0 flex items-center justify-center font-display text-[13px] font-medium text-[#E7F4F7]">{stage.count} <span className="ml-1.5 font-mono text-[9px] text-[#89A4AD]">txns</span></div></div></div>)}</div>; }
