import { Route, Switch } from "wouter";
import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import ErrorBoundary from "@/components/ErrorBoundary";
import { ThemeProvider } from "@/contexts/ThemeContext";
import LandingPage from "@/pages/LandingPage";
import { AIDecisionsPage, AnalyticsPage, AuditPage, DashboardPage, RecoveryPage, TransactionDetailPage, TransactionsPage } from "@/pages/ProductPages";
import { AppShell, PageIntro } from "@/components/AppShell";
import { Settings2 } from "lucide-react";

function SettingsPage() { return <AppShell title="Settings" eyebrow="SYSTEM"><PageIntro eyebrow="SYSTEM CONFIGURATION" title="Control the operating environment." description="Configuration and operational parameters for the ReviveAI recovery pipeline." /><div className="glass-panel max-w-2xl rounded-xl p-6"><div className="flex items-center gap-4"><div className="grid h-11 w-11 place-items-center rounded-lg border border-[#6DE7F2]/20 bg-[#6DE7F2]/[0.07] text-[#6DE7F2]"><Settings2 className="h-5 w-5" /></div><div><div className="font-display text-lg text-[#E7F4F7]">Operating Environment</div><div className="mt-1 text-[12px] text-[#78919B]">Operational parameters and gateway integrations.</div></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2"><div className="rounded-lg border border-white/[0.08] bg-white/[0.025] p-4"><div className="font-mono text-[9px] text-[#607782]">DATA PIPELINE</div><div className="mt-2 font-mono text-[11px] text-[#6DE7F2]">FASTAPI LIVE / AUTO-SYNC</div></div><div className="rounded-lg border border-white/[0.08] bg-white/[0.025] p-4"><div className="font-mono text-[9px] text-[#607782]">RAZORPAY GATEWAY</div><div className="mt-2 font-mono text-[11px] text-[#F0B36B]">TEST MODE</div></div></div></div></AppShell>; }
function NotFoundPage() { return <AppShell title="Page not found" eyebrow="404"><div className="flex min-h-[65vh] items-center justify-center"><div className="text-center"><div className="font-mono text-[10px] tracking-[.18em] text-[#6DE7F2]">SIGNAL LOST / 404</div><h2 className="mt-4 font-display text-4xl text-[#E7F4F7]">This route is not in the ledger.</h2><p className="mt-3 text-[13px] text-[#78919B]">Use the navigation to return to an active ReviveAI surface.</p></div></div></AppShell>; }
function Router() { return <Switch><Route path="/" component={LandingPage} /><Route path="/dashboard" component={DashboardPage} /><Route path="/transactions/:id" component={TransactionDetailPage} /><Route path="/transactions" component={TransactionsPage} /><Route path="/recovery" component={RecoveryPage} /><Route path="/analytics" component={AnalyticsPage} /><Route path="/ai-decisions" component={AIDecisionsPage} /><Route path="/audit" component={AuditPage} /><Route path="/settings" component={SettingsPage} /><Route component={NotFoundPage} /></Switch>; }
export default function App() { return <ErrorBoundary><ThemeProvider defaultTheme="dark"><TooltipProvider><Toaster theme="dark" /><Router /></TooltipProvider></ThemeProvider></ErrorBoundary>; }
